development:
  host: localhost
  port: 27017
  database: speedmingle-dev
  logfile: development.log
    
test:
  host: localhost
  port: 27017
  database: speedmingle-test
  logfile: test.log
 
production:
  host: localhost
  port: 27017
  database: speedmingle-prod
  logfile: production.log
    
environment: development
